apiVersion: v1
kind: Pod
metadata:
 name: nmap
spec:
  containers:
  - name: nmap
    image: quay.io/cgruver0/nmap-ubi9:latest
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - CAP_NET_RAW
        - CAP_NET_ADMIN
        - CAP_NET_BIND_SERVICE
    command: ["tail", "-f", "/dev/null"]
  restartPolicy: Never